name: wand
description: Command-line tool for generating boilerplate code for Flutter.
version: 0.2.1
homepage: https://github.com/zepfietje/wand

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.5.3
  dart_style: ^1.3.6

dev_dependencies:
  effective_dart: ^1.2.0
  test: ^1.6.0

executables:
  wand: main
