name: wand
description: Command-line tool for Flutter code generation.
version: 0.1.0
repository: https://github.com/zepfietje/wand

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.5.3

dev_dependencies:
  effective_dart: ^1.2.0
  test: ^1.6.0

executables:
  wand: main
